title: My-new-course
tagline: A brand new course on Learning Lab
description: This is a new course to help me to learn to write course.
template:
  repo: my-new-course-template
  name: my-new-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
